### ISSUE TITLE
[request] implement some more functions

### ISSUE THREAD

**Issue by eshepelyuk** [nlewo/consul-template-mock#4]
Hello, 

Could you please implement 

* [secrets function](https://github.com/hashicorp/consul-template#secrets) 
* [indent function](https://github.com/hashicorp/consul-template#indent)

from `consul-template` ?

**Comment by eshepelyuk** [comment]
Actually I was able to patch, so ready to provide PR is this project is still maintaned.

**Comment by nlewo** [comment]
Yeah, a PR would be welcomed!
Especially if add a test ;)

**Comment by eshepelyuk** [comment]
Thnx @nlewo will try to make tests as well.
